nav:
  - Tracker: index.md
  - Udemy: udemy.md
  - DeepLearning.AI: deeplearning-ai.md
  - Coursera: coursera.md
  - YouTube and Talks: youtube.md
  - Free Courses: free-courses.md
  - Live Cohorts: cohorts.md
  - Course Notes: notes
